START TRANSACTION; # 트랜잭션 시작 
# BEGIN/BEGIN WORK
USE SHOPPINGMALL;
# FOO002 가격을 2000원으로 수정
UPDATE PRODUCT SET PR_PRICE = 2000 WHERE PR_CODE = 'FOO002';

SAVEPOINT A;

UPDATE PRODUCT SET PR_PRICE = 1000 WHERE PR_CODE = 'FOO002';

ROLLBACK TO A;

COMMIT;
SELECT * FROM PRODUCT;
