# 쇼핑몰을 이용한 윈도우 함수 예제

USE SHOPPINGMALL;
# 제품을 가격순으로 정렬 ROW_NUMBER
SELECT 
    ROW_NUMBER() OVER(ORDER BY PR_PRICE DESC) AS '순서',PRODUCT.*
FROM
    PRODUCT;

# 제품을 가격순으로 정렬 RANK
SELECT 
    RANK() OVER(ORDER BY PR_PRICE DESC) AS '금액순',PRODUCT.*
FROM
    PRODUCT;
# 제품을 가격순으로 정렬 DENSE_RANK
SELECT 
    DENSE_RANK() OVER(ORDER BY PR_PRICE DESC) AS '금액순',PRODUCT.*
FROM
    PRODUCT;

# 제품을 비싼 제품, 싼 제품으로 정렬 NTILE
SELECT 
    NTILE(2) OVER(ORDER BY PR_PRICE DESC) AS '그룹',PRODUCT.*
FROM
    PRODUCT;

# 가장 비싼 제품들을 조회하는 쿼리 DENSE_RANK
SELECT * FROM (
	SELECT 
		DENSE_RANK() OVER(ORDER BY PR_PRICE DESC) AS 'pr_rank',PRODUCT.*
	FROM
		PRODUCT
) AS RANKED_PRODUCT
WHERE PR_RANK = 1;
